### ISSUE TITLE
Is there a need to keep the RedEyes version?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#1057]
Because if we drop the support of Red Eyes version, the deployment script and so on will be simpler.

**Comment by LefterisJP** [comment]
Red eyes is still the only contract deployment we have on the mainnet. As such it has to be supported in this repo. Supported means to just keep the data here. After a new mainnet contracts release is made and the deprecation switch is activated perhaps we can re-discuss this.

But also then, for historical purposes it would be good to at least have somewhere the source/bytecode/abi.

The ability to deploy them can go away though ... even now, since we don't want anybody deploying them again I assume.

**Comment by pirapira** [comment]
I think the approach is correct to start with the use cases.

* Some people install `raiden-contracts` from `raiden:master`.  For these people right now, the RedEyes deployment data is the only interesting thing.  Do we sometimes want `raiden:master` to update the `raiden-contracts` version?  Possibly yes.  There can be a mistake in the stored ABI etc.
* Some people install `raiden-contracts` from `raiden:develop`.  For these people anything RedEyes is not interesting.
* Some people might try to deploy `raiden-contracts` somewhere on themselves.  Maybe they are assessing whether to start using RedEyes on mainnet, but first trying on a private network.

**Comment by pirapira** [comment]
The conclusion seems like "at least until a new mainnet deployment is available".  Then we'll think about it again.
