### ISSUE TITLE
Cooperative settlement (simple implementation and clear old code)

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden-contracts#1383]
https://github.com/raiden-network/raiden-contracts/issues/399 was commented out to be re-enabled in the future, but after a discussion with @karlb we realized that withdraw alone provides the same capabilities as coop settle. Instead of having two primitives it makes more sense to just have one.

The only drawback is that two withdraws would be more expensive then a single coop settle. This has to be measured and weighted to see if it is significant enough to keep coop settle around.

**Comment by karlb** [comment]
I've done some measurements to compare the gas cost of different approaches:

## Classic Approaches

### Two Withdraws
Don't implement anything new and expect both parties to do a withdraw if they don't want to use the channel, anymore.
Gas cost: 2 * 109_565 = 219_130
Result: open, empty channel

### Coop Settle
Activate the cooperative settle function which is currently disabled in the contract. The code to handle coop settlement in Raiden is still missing, but would look similar to our current withdraw code.
Gas cost: 60_857
Result: settled channel

## Hybrid Approaches

These two approaches reuse our current withdraw signatures, but both nodes coordinate to only have a single on-chain transaction. That reduces the number of different proofs we have to handle compared to the original coop settle, but apart from that is about as complex.
Potential attack: Instead of executing both withdraws, the transaction submitter could initiate only one withdraw (relatively harmless)

### Two Withdraws in a Single Transaction
Add a small wrapper function to execute both withdraws in a single transaction.
Gas cost: 154_140
Result: open, empty channel

### Coop Settle Based on Withdraw
Reuse the existing code to create and check withdraw proofs in a new coop settle function. The function would check both withdraw proofs, but instead of withdrawing, it settles the channel. 
Gas cost: ~100_000
Result: settled channel

**Comment by palango** [comment]
@karlb Which of the hybrid approaches was the one that you and Augusto favored?

**Comment by karlb** [comment]
I don't think there was a clear favorite, but I would suggest going with "Coop Settle Based on Withdraw".

**Comment by palango** [comment]
Also discussed in https://github.com/raiden-network/raiden-contracts/issues/1236

**Comment by palango** [comment]
Fixed by https://github.com/raiden-network/raiden-contracts/pull/1474
