### ISSUE TITLE
Raiden on Arbitrum: remove settle_timeout from channel state and events

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/raiden-contracts#1582]
#1557 removed the variable settle timeout, but still left it in the channel state, wasting gas (store is expensive). We want to remove the `settle_timeout` constant (per deployment) from all stores/mappings and events, to save gas, and to ensure clients fetch the global value directly from the contracts from now on.

One reason why it's still in channel state/struct is because this variable is reused to store the point in time after which the channel becomes settleable. A possible implementation is to have this timestamp persisted in a separate mapping, which also gets cleared upon settlement. Notice that this saves gas by not needing the store space/write operations on channel open, and if the channel gets coop-settled, actually never gets set.

**Comment by netcriptus** [comment]
I think there might be some confusion going on here. #1557 didn't remove `settle_timeout`, it introduced the variable to replace the previously configured range from `settle_timeout_min` to `settle_timeout_max`, so now we have a more precise timeout configured.

On top of that, #1573 switched this variable to store an actual timestamp instead of a block number.

As such, we can't get rid of the `settle_timeout` variable, because it is being used in quite a few places.

**Comment by andrevmatos** [comment]
`settle_timeout` isn't expected to go away, it needs to exist, but now it should be just a contract's constant, instead of specific per channel. This issue is about removing all places where it's still channel-specific, like a copy of this constant on every `Channel` struct instance, and it being emitted in the `ChannelOpened` event. Removing these will save some gas, and anyone interested in the value should fetch it from the contract's method.

**Comment by andrevmatos** [comment]
Fixed by #1586 in `arbitrum` branch
