### ISSUE TITLE
Providing a balance proof with a transferred_amount bigger than the deposit should fail

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#17]
At the moment, providing a `transferred_amount` > participant's `deposit` does not fail. 
This should fail and the settlement logic should be reviewed to make sure it is correct.

**Comment by hackaugusto** [comment]
No, it should not, transferred_amount is monotonically increasing and it will most likely be **way large** than the total deposit of the channel. Under an uncooperative close either balance proof may not be provided, making the netted value way larger than the total deposit.

**Comment by LefterisJP** [comment]
@loredanacirstea note here that the transferred amount can end up being quite larger than the deposit for channels with lots of back and forth as it's always increasing.

So picture a channel A - B with both A and B having deposited 5.

A -> B (sends 5)  -- A to B transferred_amount is now 5
B -> A (sends 5)  -- A to B transferred_amount is now 5
A -> B (sends 5)  -- A to B transferred_amount is now 10

Deposit is always 5 but due to the transferred_amount monotonically increasing we easily end up with transferred_amount bigger than the deposit.


Note: Is this the test that you showed me in the code needs to be checked even in the current behaviour? If so then we got no problem with the current behaviour.

**Comment by loredanacirstea** [comment]
Yes, I did not think this through. There is no issue.
