### ISSUE TITLE
Architecture decision - unlocking pending transfers on-chain

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#202]
Also related to the channel lifecycle issue here https://github.com/raiden-network/raiden-contracts/issues/193

I wanted to describe the `unlock` issue in more detail.

## Current channel lifecycle start & end:
1. openChannel
2. a) closeChannel & settleChannel 
    - remove channel data
    - we might have `unlock` data remaining in the contract in a separate mapping
    - new channel can be opened between the same participants
2. b) cooperativeSettle 
    - remove channel data
    - no `unlock` data remains in the contract
    - new channel can be opened between the same participants

The issue appears for 2.a), when we can have a totally different channel open and possibly multiple `unlock` data for multiple channels.

## PROs:
- pending transfers can be `unlock`ed at a later time or not at all, depending on the value of tokens vs. gas needed for the transaction
- transaction gas cost is somewhat fair: each participant can pay for the `unlock` that favors him, `settleChannel` (that potentially transfers the biggest amount of tokens) costs less gas due to clearing up storage.

## CONs:
- channel lifecycle is not simple anymore -> adds complexity in the Raiden client or any client that might be implemented

## How we ended up here:
- batch unlock discussions (why we wanted it): https://github.com/raiden-network/spec/issues/35, https://github.com/raiden-network/spec/issues/31, 
- batch unlock implementation: https://github.com/raiden-network/raiden-contracts/pull/39, with this thread also in mind: https://github.com/raiden-network/raiden-contracts/pull/39#discussion_r183750230 about the lifecycle issue and proposal of solution 2.

### 1. Do nothing 
and we will keep having channel lifecycle issues. Also keep in mind my two comments from https://github.com/raiden-network/raiden-contracts/pull/198#discussion_r206465782 & https://github.com/raiden-network/raiden-contracts/pull/198#discussion_r206465857

### 2. Remove channel data after both `unlock`s
, forcing participants to do the two on-chain transactions IF they want to open a new channel

- suggested by @hackaugusto also in https://github.com/raiden-network/raiden-contracts/pull/39#discussion_r183750230
- `settleChannel` transaction will become more costly
- last `unlock` will become less costly (gas returned for removing more storage - channel data)
- `unlock` data can be kept in the channel `struct`
- channel lifecycle end is clear
- Raiden client will have less complexity by not being forced to keep additional `unlock` data for (maybe) multiple channels
- needs refactoring in `TokenNetwork` contract (more than 3.)
- needs some Raiden client refactoring (not sure how much compared to 3.)

### 3. Make it clear that for a specific `channel_identifier`, we have `unlock` data in storage.
- keep current way being able to `unlock` at any point in time or not at all
- transaction gas cost is somewhat fair (see `PROs`)
- channel lifecycle end is not clear, but it might be enough to clarify a channel's state if we link the `unlock` data with the `channel_identifier`
- Raiden client needs to either keep `unlock` data separately (probably easier) or support multiple channels opened at the same time (something that we discussed before and wanted, but we changed our minds at some point)
- needs some refactoring in the `TokenNetwork` contract, as described below:

https://github.com/raiden-network/raiden-contracts/pull/198 is not enough;
We also discussed https://github.com/raiden-network/raiden-contracts/issues/193#issuecomment-407689046 but that is not totally correct.

After thinking about this, we can have:
```js
    // The key is `keccak256(uint256 channel_identifier, address participant, address partner)`
    // Where `participant` is the participant that sent the pending transfers
    // We need `partner` for knowing where to send the claimable tokens
    mapping(bytes32 => UnlockData) unlock_identifier_to_unlock_data;

    struct UnlockData {
        // Merkle root of the pending transfers tree from the Raiden client
        bytes32 locksroot;
        // Total amount of tokens locked in the pending transfers corresponding to the `locksroot`
        uint256 locked_amount;
    }

    function unlock(
        uint256 channel_identifier,
        address participant,
        address partner,
        bytes merkle_tree_leaves
    )

```
The next question is about our state getters. 
After https://github.com/raiden-network/raiden-contracts/pull/198 we have:
```js
// ! returns (settle_block_number, state)
function getChannelInfo(uint256 channel_identifier) view external returns (uint256, uint8)

// returns: deposit, withdrawn_amount, is_the_closer, balance_hash, nonce
function getChannelParticipantInfo(uint256 channel_identifier, address participant)
```
If we want to include the `unlock` data somewhere, we can include it in `getChannelParticipantInfo` for example. Then, this will look like:
```js
// returns participant's: deposit, withdrawn_amount, is_the_closer, balance_hash, nonce, locksroot, locked_amount
// `participant` - sends the pending transfers
// `partner` - receives claimable locked amount from `participant`'s transfers
function getChannelParticipantInfo(uint256 channel_identifier, address participant, address partner)
```

Questions that may influence the decision through economic incentives:
a) who does the two `unlock`s on-chain?
 - each `participant` `unlock`s his own pending transfers that he has sent
- each `participant` `unlock`s his `partner`'s pending transfers that he might receive
- Raiden client checks what pending transfers are most valuable to the `participant` based on the `claimable` and `unclaimable` amount of tokens and does the `unlock` automatically.

**Comment by loredanacirstea** [comment]
@hackaugusto , @LefterisJP,  @rakanalh ?

**Comment by loredanacirstea** [comment]
We have not actually considered solution 2 that much until now. I think we should, otherwise we might end up discussing the same problem after we consider the contracts finalized. 
In my opinion, better discuss & decide now rather than after an audit.

**Comment by LefterisJP** [comment]
Hey Loredana. 

## Discussion of approach 2

### Questions

So you want to have logic in `unlock()` that deletes the channel data for the participants from the [channels mapping](https://github.com/raiden-network/raiden-contracts/blob/dfb37c7962a17e72b1b44d1d301db3b0e8fd6483/raiden_contracts/contracts/TokenNetwork.sol#L36) once both sides have deleted the pending transfers, is that right?


>  forcing participants to do the two on-chain transactions IF they want to open a new channel

So by this you mean that if the people want to open a new channel they will be forced to call unlock on their pending transfers even if that makes no sense due to a dust amount, right?


### Comments

> Raiden client will have less complexity by not being forced to keep additional unlock data for (maybe) multiple channels

We already have an issue for [this](https://github.com/raiden-network/raiden/issues/1941) in the client as a direct result of our conversation about this [last week](https://github.com/raiden-network/raiden-contracts/issues/193#issuecomment-407452623). So this is actually being worked on. I don't want to have to undo this work again.

> needs some Raiden client refactoring (not sure how much compared to 3.)

Yes it will need quite a bit of work, and can't answer with certainty until I (or augusto) sit down look at the code and think of what needs to be changed.

## Opinion on approach 2

Keep in mind we are going to make more changes on the contracts after red eyes mainnet release so this can be scheduled for then if we deem it necessary. We also have set ourselves a rough date of summer 2018 which already seems rather hard to hit as it is. Adding more tasks at this point is going to make it near impossible to finish on-time.

I also don't like the idea of having to force users to unlock pending transfers if they want to open a new channel with the same participant. I find it a useful feature of the current approach that they have a choice.

At the moment my feeling is to not go with this at this time.

But I note your concern [here](https://github.com/raiden-network/raiden-contracts/issues/202#issuecomment-409178013):

> I think we should (I also think it is a good option), otherwise we might end up discussing the same problem after we consider the contracts finalized.

and I would like to ask in what ways do you think the current way would manifest in a problem later if we implement the changes discussed in #193 for the smart contracts and for the client the issues described [here](https://github.com/raiden-network/raiden/issues/1907#issuecomment-407565857).

## Questions on approach 3

> transaction gas cost is somewhat fair (see PROs)

As per my comment on approach `2`, I like the current way of allowing to unlock or not unlock at all so I like this pro.

> but it might be enough to clarify a channel's state if we link the unlock data with the channel_identifier

So this is what you are describing at the end of your comment with the source code snippet, right? To include the unlock data here:

`function getChannelParticipantInfo(uint256 channel_identifier, address participant, address partner)`?


## Opinion on approach 3

So the only proposed change here is to link unlock data with channel identifier so that it's clearer to query a channel state? That sounds doable and useful.

## Question on who does unlocks on chain

> each participant unlocks his partner's pending transfers that he might receive

^ This is the way that we currently [do](https://github.com/raiden-network/raiden/blob/bf8da6c0a362416682e5b42d36800f4e0e7c2d46/raiden/transfer/channel.py?utf8=%E2%9C%93#L1725) it in the raiden client.

It's far from optimal.

> Raiden client checks what pending transfers are most valuable to the participant based on the claimable and unclaimable amount of tokens and does the unlock automatically.

I think either asking the user for input at this point or the user having some kind of setting she can customize about the amount above which pending transfers should be unlocked would make sense

**Comment by loredanacirstea** [comment]
> Discussion of approach 2 - Questions

Correct.

> and I would like to ask in what ways do you think the current way would manifest in a problem later if we implement the changes discussed in #193 for the smart contracts and for the client the issues described here.

Not sure, because I don't have good enough view on the Raiden client as you or @hackaugusto . But roughly, it would be related to `Raiden client [..] being forced to keep additional unlock data for (maybe) multiple channels`

> Questions on approach 3 & Opinion on approach 3

Correct.

**Comment by hackaugusto** [comment]
First a clarification, this issue is about the definition of the life cycle of a channel, correct?

For the channel life cycle there are a few things to take into account:

1. Are two participants allowed to have multiple channels open at the same time?
2. How do we detect if an operation the node wants to perform is still valid?
  2.1 And how do we identify the on-chain channel

It seems the discussion here is about 1. and not 2.

With that said, IMO the channel life cycle discussion started with issue https://github.com/raiden-network/raiden-contracts/issues/40 "Disallow multiple channels between two nodes" . It was decide to forbid multiple channels because having it would "[...] require changes in the Raiden API and the PFS". If the goal was to do the above then the life cycle of channel should have been as the following diagram:

![g](https://user-images.githubusercontent.com/310139/43463528-28ddbb60-94af-11e8-96c7-ca022a37947a.png)

And a new channel should only be available after *both unlocks* or *coop settle*. Having a pending operation for a channel (unlock) while another channel is opened means there **are** multiple channels open at the same time, which effectively means the goal of issue #40 to reduce the impact on the Raiden code base was not achieved (https://github.com/raiden-network/raiden/issues/1941).

The goal of issue #40 was not technical, but to save development time, so I don't have much more to say about it.

**Comment by loredanacirstea** [comment]
So, then @hackaugusto , what is your position on:

> Are two participants allowed to have multiple channels open at the same time?

regardless of what decisions we already made?

**Comment by LefterisJP** [comment]
> Are two participants allowed to have multiple channels open at the same time?

I believe we already discussed this and I really don't see any compelling upside to allowing this for the near term release. 

If some external feedback or input comes and proves otherwise then we can reconsider but with the current limited data we have I don't see this worth the hassle.

The only upside of the approach of multiple channels is that you don't have to wait for the close/settle in order to open a new channel with the same peer. Are there any other benefits?

**Comment by loredanacirstea** [comment]
Fixed through https://github.com/raiden-network/raiden-contracts/pull/203
