### ISSUE TITLE
Store contract source hashes

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden-contracts#291]
As suggested by @hackaugusto 

1) in `setup.py compile_contracts` perform two actions - compile the json abi+bytecode + store hash of contract source files in the json
2) in `setup.py build` compare hashes from the json abi. Abort if they don't match.

This should prevent bugs like #280 or situations where the compiled abi differs from the updated source.

**Comment by hackaugusto** [comment]
Actually I was proposing to remove the commands from the setup.py and have the CI system ensure the json files are available in the filesystem and matches the existing smart contracts.

**Comment by loredanacirstea** [comment]
After yesterday's discussion with @hackaugusto and as mentioned in https://github.com/raiden-network/raiden-contracts/issues/291#issuecomment-425879878:

- `contracts.json` will be included in `master` and updated on every source code change
- `contracts.json` will contain the ABIs, bytecode & source code checksums, in order to verify that the existing compiled file matches the existing source code
- `raiden-contracts` package installation will not compile the contracts, but it will do the above verification
- add a CI contracts verification test
- run the verification test before uploading the package to pypi

Proposed by @konradkonrad :
- check the `solc` version with which the contracts were compiled

**Comment by LefterisJP** [comment]
@loredanacirstea Sounds good. So the generation of contracts.json should be done manually by someone with solc?

Can contracts.json also contain the version of solc used?

**Comment by loredanacirstea** [comment]
Yes, the generaltion of `contracts.json` should be done by someone with `solc` - the person who last changes the source code. Otherwise, tests will fail because the checksum verification will fail.

We can add the solc version to `contracts.json` and I think it is a good idea. It does not currently contain it. But I would make another issue & PR for this and not include it in https://github.com/raiden-network/raiden-contracts/pull/295.
