### ISSUE TITLE
Add deployed contract addresses

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#299]
We need to add the addresses of the deployed contracts for all chains (Mainnet + testnets).

We can add them in https://github.com/raiden-network/raiden-contracts/blob/de291393bcbc8372a3d3e9b2cbe2bfd4effc6993/raiden_contracts/constants.py

The Raiden client should use these addresses when running.

**Comment by LefterisJP** [comment]
We already [do](https://github.com/raiden-network/raiden/blob/89190f86cbe9b7cbfa78e10314ba1aafc3e9c663/raiden/constants.py#L35) that in the Raiden client, [categorize them depending on the network](https://github.com/raiden-network/raiden/blob/89190f86cbe9b7cbfa78e10314ba1aafc3e9c663/raiden/constants.py#L80) and also have [an argument](https://github.com/raiden-network/raiden/blob/89190f86cbe9b7cbfa78e10314ba1aafc3e9c663/raiden/ui/cli.py#L408) that's used to switch between the different configurations [when raiden starts](https://github.com/raiden-network/raiden/blob/89190f86cbe9b7cbfa78e10314ba1aafc3e9c663/raiden/ui/cli.py#L707-L776).

I would like to keep it that way. Don't see a reason to have the deployed addresses here.

**Comment by loredanacirstea** [comment]
I consider official deployed addresses as part of the package deliverables. 

Also, aside from the Raiden client, they will also be used by the 3rd party services (e.g. Monitoring Service using the deployed addresses from the MS contract etc.) and by other client implementations or extensions that anyone might build.

**Comment by LefterisJP** [comment]
> I consider the officially deployed addresses as part of the package deliverables.

I have not considered this as part of this package especially since we never had it here so far.

> Also, aside from the Raiden client, they will also be used by the 3rd party services

But this is a valid reason to have them here.

I then agree to moving them here. No need to duplicate code/addresses across packages.

But then the deployment block of the contracts should also be moved. Do you agree we should then move the entire network configuration as seen [here](https://github.com/raiden-network/raiden/blob/89190f86cbe9b7cbfa78e10314ba1aafc3e9c663/raiden/constants.py#L80) in the client?
