### ISSUE TITLE
make compile_contracts should also compile contract/services?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#365]
Currently, `make compile_contracts` compile only `sol` files in `contracts` and `contracts/test`.  When I change a file in `contracts/services`, I don't get any update in `contracts.json`.  Is this intended?  Or should `contracts/services` be also compiled?

**Comment by loredanacirstea** [comment]
I answered here: https://github.com/raiden-network/raiden-contracts/pull/360#issuecomment-444880974, where a discussion on this was already started. 
tl;dr: we can include them in the compiled data.

The services contracts were left out because they were scoped out of Red Eyes and work on them was discontinued.

**Comment by pirapira** [comment]
OK.   Sorry for the duplicate.

**Comment by loredanacirstea** [comment]
Ah, it is not really a duplicate, as the discussion was on an unmerged PR. I would leave this issue open, because it describes the problem more clearly.

**Comment by loredanacirstea** [comment]
https://github.com/raiden-network/raiden-contracts/pull/360 was merged. Service contracts were included in the compiled data, because this is what the `raiden-contracts` package exports for other projects to use.
