### ISSUE TITLE
Installing contracts on private network

### ISSUE THREAD

**Issue by offerm** [raiden-network/raiden-contracts#397]
I'm trying to setup private ethereum network and raiden network.

currently stuck with raiden-contacts setup.

I'm using a fresh ubuntu 18.10 machine. The machine is coming with Python 3.6.7 installed but has no command `python`. It has `python3`, `python3.6`.

`pip` is not installed.

the installation of `pip` needs `python` (https://pip.pypa.io/en/stable/installing/). 

What should I do now? 
@loredanacirstea

**Comment by offerm** [comment]
I managed to progress until I got to #398 

Will update what I did.

**Comment by offerm** [comment]
Before successfully creating the contracts, token and registration of the token I had to do the following: (was done on a fresh Ubuntu 18.10 install)

1. install geth and setting a private network (not covered here)

2. "create" soft link for python

sudo ln -s /usr/bin/python3.6 /usr/bin/python
install python3-distutils

3 .sudo apt install python3-distutils

4. install pip

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python get-pip.py

5. install gcc

sudo apt install gcc

6. install python3-dev

sudo apt install python3-dev
7. install solc 0.4.25
Download solc binary from https://github.com/ethereum/solidity/releases
make sure not to use 0.5.x
rename the executable and call it solc
chmod+x solc to make it runnable 
move solc to /usr/local/bin 
check with "solc - version"

8.  Raiden-Contracts
clone the repository and checkout v0.8.0

cd
git clone https://github.com/raiden-network/raiden-contracts.git
cd raiden-contracts
git checkout v0.8.0

9. install requirements 

sudo pip install -r requirements-dev.txt

10. running raiden, token, register, verify

Notes: 
1. verify will fail and it is OK to ignore it.
2. if you execute `register` twice it will generate a `gas error`
3. if you start geth with `--networkid` which is different from `chainId` you get a `invalid sender` error.

The setup instructions at https://github.com/raiden-network/raiden-contracts are not clear. It is not clear that:

1) no need for make install 
2) no need for make verify_contracts 
3) **need** to run pip install -r requirements-dev.txt 
4) no need for make compile_contracts 
5) it is OK if python -m raiden_contracts.deploy verify fails.


I suggest a writeup of the setting page.

**Comment by loredanacirstea** [comment]
> verify will fail and it is OK to ignore it.

This is not ok. As I said in gitter:

> should not fail ideally, but the current bytecode check is not implemented correctly (does not account for various system versions etc.), so for now, this is acceptable until mitigated as I mentioned above.

Opened an issue to document this: https://github.com/raiden-network/raiden-contracts/issues/408, we are working on a fix.

> 7. install solc 0.4.25

Indeed, there was a bug in the deployment script that forced contracts to be recompiled. This will be fixed with https://github.com/raiden-network/raiden-contracts/pull/407

> if you execute register twice it will generate a gas errorv

Added a note in Readme about this: https://github.com/raiden-network/raiden-contracts/pull/406/commits/a4d748a2d3b812a6d8665c3068625bb534d3909d

> if you start geth with --networkid which is different from chainId you get a invalid sender error.

Added a note in Readme about this: https://github.com/raiden-network/raiden-contracts/pull/406/commits/09c0e2255533f0911545c6312adaf08511799c6c

> The setup instructions at https://github.com/raiden-network/raiden-contracts are not clear

Should be fixed by https://github.com/raiden-network/raiden-contracts/pull/409. I made the deployment as a standalone subheader, mentioning only the dev dependencies installation.

**Comment by loredanacirstea** [comment]
> if you execute register twice it will generate a gas error

Ah, I misread this. Registering the same token twice will always fail.
However, registering a second **different** token will also fail now. This is a temporary legal limitation unfortunately for the Red Eyes Mainnet release.

**Comment by loredanacirstea** [comment]
@offerm let me know what you think about the above readme changes.

**Comment by loredanacirstea** [comment]
@offerm also, if you still have it, please send us the `data/contracts.json` file that you created by recompiling the contracts (attach in a comment / gist). It would help us reproduce the bytecode verification issue here: https://github.com/raiden-network/raiden-contracts/issues/408

**Comment by loredanacirstea** [comment]
@offerm , ok, I see what the issue was now:

1. `Before compile`

- (1) deployment script was compiling the source code itself and deploying this new precompiled data
- (2) the deployed source code was different than the one in the official `data/contracts.json`

2. `After compile`

- (1) `data/contracts.json` changed with the new compiled data
- (2) deployment script was compiling the source code itself and deploying this new precompiled data
- (3) the deployed source code (2) was the same as (1) and this is expected

So the question is why do we have a different official `data/contracts.json` than the one you compiled at points 1.(1), 2.(1), 2.(2).

I will look into the provided compiled data, thank you.

But just to exclude this: did you change anything in the Solidity source code?

**Comment by pirapira** [comment]
`solc` should be 0.4.23 not 0.4.25 (judging from `pragma solidity ^0.4.23;` in `TokenNetwork.sol`).

**Comment by offerm** [comment]
No, Changed nothing so far.... I may do later as I need to support two Tokens.

**Comment by loredanacirstea** [comment]
I actually used `0.4.25` to compile the official `data/contracts.json`

**Comment by offerm** [comment]
^0.4.23 mean and 0.4.x version providing x>=23. @pirapira

**Comment by pirapira** [comment]
I see.

**Comment by loredanacirstea** [comment]
@offerm , I was under the impression that I did not add support for the no_limits version - sorry for this.

You can try using `--contracts-version "pre_limits"` when deploying `raiden`. This should use the `data_pre_limits/contracts.json` which does not have the ` token limitation.

**Comment by offerm** [comment]
@loredanacirstea 
when  using the pre-compiled contracts I can start raiden.
If I compile the contracts locally and try to use raiden I face errors. looks to me that the pre-compiled contracts has version 0.3.0 while the source code is 0.4.0

**Comment by loredanacirstea** [comment]
This is correct. The Raiden client should support this in `--development` mode.

**Comment by loredanacirstea** [comment]
Can this issue be closed? I think I covered the problems - either opening separate smaller issues or doing the fixes.

**Comment by offerm** [comment]
OK by me.
