### ISSUE TITLE
Add batching of transactions for opening a channel & depositing 

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/raiden-contracts#400]
We can have a wrapper for opening a channel and depositing. This lowers the waiting time for the user, as it reduces the number of on-chain transactions from 2 to 1.

**Comment by hackaugusto** [comment]
This not only improves the wait time, but it also simplifies the handling of smart contract proxies. Specifically the ERC20 token networks a client has to:

- Use a global lock to synchronize usage to a token and to its corresponding token network. This is necessary because calls to `approve` are not idempotent, and concurrent calls will race, making one of them fail.
- It's necessary to validate multiple conditions before doing a deposit, on both the token and the token network state, and the interactions lead to cumbersome code.

[reference](https://github.com/raiden-network/raiden/blob/1466689bd21bf7a4e285784bc502b3620fdc44ba/raiden/network/proxies/token_network.py#L493-L664)

**Comment by pirapira** [comment]
Note: consider implementing the proxy in a separate contract.  We are close to hitting the deployed codesize limit.

**Comment by palango** [comment]
Closed in https://github.com/raiden-network/raiden-contracts/issues/1436
