### ISSUE TITLE
General SC questions

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-contracts#454]
### Function return values

ERC20 uses a boolean return value for the `transfer` functions. Many other functions use `require` and just fail when the intended action does not happen. Is there an obvious rule when to choose which behaviour? I could only think of "when the function is used by other functions a return value will allow better composability, for all other cases a failing transaction is easier to handle and avoids silent errors".

Related to this: do return values make sense for functions which I expect to be directly called via `transact`?

### Blocks or time

Currently we use block numbers for the settlement timeout. Do we generally want to use block counting for timeouts? Using `block.timestamp` is another candidate and might be more future proof regarding changes in Ethereum block creation, since timeouts are meant to have a certain real world duration.

### Passing a list of trusted contracts

When a contract is supposed to trust multiple other contracts, what is the best way to handle that? Taking and saving an array of addresses (less duplication, more generic) or a fixed number of separate variables (maybe less gas cost when checking?)

### Events

Do we want events only in cases where they are strictly necessary (when other processes need to be informed)? Events make it easier to write reliable tests in some cases and will probably also make it easier to debug some problems occurring in production.
Events can also make it easier to reliably check that a transaction worked as intended, since transactions don't have return values and checking for the effect might introduce errors due to concurrency.

How much data should be put into an event? If we have a BalanceChanged event, it would be expedient to add the new balance. But if we leave out the balance we save a bit of gas and the process can always do a free function call to check the latest balance, which should be good enough.

### Freeing storage space

When storage space is freed, some gas refund is granted. But if we add a `cleanup` function just for freeing storage, it would make no sense to call it directly in a transaction, since the caller won't get any ether back. I can think of two ways to deal with it:
* Expect functions in other contracts to call your cleanup after doing work to save some gas. Due to the cost of calling functions in other contracts this is probably not that lucrative.
* Integrating cleanup options in the normal functions of your contract.

Is this correct, or am I missing something?

**Comment by pirapira** [comment]
> Function return values

Failure has one advantage; the caller can be sure that the callee has reverted its storage contents.  But "return false v.s. revert" often causes bike-shed arguments.

> Blocks or time

Miners can choose the timestamp (some people say the timestamp can be tampered up to 900 seconds; I don't believe that much).  That puts additional trust on the miners.

**Comment by loredanacirstea** [comment]
> Function return values

Agree with @pirapira. 
My take on this: if you plan for composability, where you **want** the transaction to pass regardless of some internal failures, then use `return`. An example: https://github.com/raiden-network/raiden-contracts/blob/5c87abb3e11337d5373afaf541e08a403a78ab39/raiden_contracts/contracts/SecretRegistry.sol#L30-L41
If a silent failure is bad, then `require`. My personal default is to fail fast, because I see it as a more secure practice. 

> Blocks or time

My preference is `blocks`. I consider this the default for blockchain and it is generally preferred (mostly due to what @pirapira said)

> Passing a list of trusted contracts

Depends on how many, but I guess you are asking with our use case in mind.
An array might be useful if we allow multiple tokens for payments - the `MSC`, `PFSC` are bound to a certain token (in the current specs) or if we figure out in the future that we need more services (more extensible).
Cannot say for sure what would be better now.

> Events

My default is now: start with as many events (& arguments) as you think you might need, without over thinking optimizations. But keep in mind where you can optimize later if needed. This also depends on wether you build the app based on `events` or based on `storage`.

> Freeing storage space

My default on this: `Integrating cleanup options in the normal functions of your contract`. E.g. removing the channel data when not needed anymore https://github.com/raiden-network/raiden-contracts/blob/5c87abb3e11337d5373afaf541e08a403a78ab39/raiden_contracts/contracts/TokenNetwork.sol#L728-L734
Note that you must remove it if you are sure you don't need it anymore. This particular example sparked some discussions and some proposals were to remove it later in the channel cycle (in `unlock` for example).
My arguments for keeping the cleaning inside the "normal" functions are:
- you can make a clean lifecycle if you plan it well enough
- the user benefits from freeing up storage (especially if he paid for the gas in the first place)

**Comment by pirapira** [comment]
@karlb please close the issue if the answers work for you.
