### ISSUE TITLE
Participant addresses in `claimReward`

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-contracts#598]
Currently, `MonitoringService.claimReward` takes participant addresses in addition to the `channel_identifier`. The addresses get passed on to `TokenNetwork.getChannelInfo` to check if the channel has been settled.

This function signature allows sending inconsistent information (participant addresses which are not the participants of the given channel) and does not check consistency. This seems problematic to me. Is this an oversight, or is there a reason for this?

I've noticed that some functions in `TokenNetwork` also take both participants and the channel_id as parameters and then do
```
require(channel_identifier == getChannelIdentifier(participant, partner));
```
If I pay the gas cost for `getChannelIdentifier` anyway, why do I still require `channel_identifier` as a parameter?

**Comment by pirapira** [comment]
At least a simpler signature `unlock(address participant, address partner)` would not work.  Between the same two addresses (say `Alice` and `Bob`), multiple `channel_identifier` can be assigned over time within the same `TokenNetwork`.  Also, these multiple channel_identifier can be relevant at the same time.

1. a channel opens for Alice and Bob (gets channel_id == 7)
2. Alice and Bob close and settle the channel (id 7) but forget to `unlock()` some pending transfers.
3. a new channel opens for Alice and Bob (get channel_id == 12)
4. Alice and Bob close and settle the channel (id 12) but fortget to `unlock()` some pending transfers.
5. `unlock(7, Alice, Bob)` and `unlock(12, Alice, Bob)` do different tings.

For the same reason `getChannelInfo(address participant, address partner)` would not work because this function looks at the pending transfers that can be unlocked now.

Does this answer the question?

**Comment by pirapira** [comment]
> If I pay the gas cost for `getChannelIdentifier` anyway, why do I still require `channel_identifier` as a parameter?

This is a prevention against Alice talking to an old channel (`channel_id == 7`) with Bob when she should be talking to a newer channel with Bob (`channel_id == 12`).

**Comment by pirapira** [comment]
@karlb do these make sense?

**Comment by karlb** [comment]
Yes, that makes sense. But I'm still skeptical that our current `claimReward` implementation is safe. By providing random addresses for `closing_participant` and `non_closing_participant`, I could trick `claimReward` into believing that the channel is settled even when it is not. Or do I miss anything that prevents such an attack?

**Comment by pirapira** [comment]
I see.  We have to note that `getChannelInfo()`s return values can be gamed. An attacker can control `Settled` vs. `Removed`.  Even when there are pending locked transfer that can be `unlock`ed, an honest caller of `getChannelInfo` gets `Settled` but an attacker can tweak addresses to get `Removed`.

Now the question is if `claimReward` should care about the distinction between `Settled` and `Removed`.  Either case, some monitoring service did the job.

**Comment by karlb** [comment]
> Now the question is if claimReward should care about the distinction between Settled and Removed.

I don't think it should. As long as the distinction between closed and settled/remove works reliable, this is OK. From reading the code, this is the case.
