### ISSUE TITLE
Test integration with raiden without releasing a pypi package

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#660]
@rakanalh has some ideas around this.  I'll ask and document them.

**Comment by rakanalh** [comment]
The idea behind this is as simple as doing exactly like: https://github.com/raiden-network/raiden/pull/3646/

Provided that Raiden client is a user of the contracts, if nothing breaks, then contracts are released. Otherwise, 
- Any breaking changes in the contracts need some rework in the client so first step is to adapt the client to changes in the contracts
- Once the client is changed, then the contract changes can be tested agains the collection of integration tests we have to make sure no bugs are introduced by the contracts.

**Comment by pirapira** [comment]
So first file a PR in `raiden` and then release?

**Comment by rakanalh** [comment]
pretty much... but the requirements for `raiden-contracts` has to point to the "latest" master... which means that the PR is not mergable but creating the PR would trigger Raiden's integration tests.

**Comment by pirapira** [comment]
Is there a way to point `requirements.txt` to a particular git commit?

**Comment by rakanalh** [comment]
Sure, you can refer to: [pip's VCS support](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support)

**Comment by pirapira** [comment]
I'd first make a release and file a mergeable PR to `raiden`.  Because this way, I have to prepare only one PR.  By the proposal, two PRs need to be prepared.  One with the VCS version and the other with the PyPI release.
