### ISSUE TITLE
Use idempotent deposit function in MS contract?

### ISSUE THREAD

**Issue by czepluch** [raiden-network/raiden-contracts#76]
Comment from Loredana:

> In the TokenNetwork contract we have decided to use an idempotent setDeposit function, which receives the total amount of tokens that should end up as deposited in the contract, instead of the amount that is added when calling the function. The main reason for this was to ensure that you don't deposit tokens by mistake, due to an additional API call.
I think we should be consistent and also use this approach here.

See how it's done in the TokenNetwork contract and implement similar functionality in the MS contract.

---

edit by @pirapira: In MSC and UDC, currently, `deposit(totalDeposit)` can cause more-than-expected deposits.  This `totalDeposit` pattern works in `TokenNetwork` because it has only-ever-increasing `totalDeposit`.  In MSC and UDC, `balance[user]` might decrease as well.

**Comment by czepluch** [comment]
@err508 remember to assign yourself to an issue when you start working on it.

**Comment by pirapira** [comment]
Though, is this really a good idea in MSC and UDC?  The "idempotent" version has the following attack vector.  The user might end up depositing more than they wanted.

1. a user sends a `deposit()` transaction
2. the transaction is seen worldwide in the pending transaction pool
3. MSC (or somebody operating MSC) decides to move tokens out of `balances[beneficiary]`, and sends a `transfer()` call
4. a miner includes MSC's `transfer()` call.  Now `balances[beneficiary]` is smaller than the user thought.
5. a miner includes the user's `deposit()` transaction.  The user pays more than expected.

This attack does not work in `TokenNetwork` because the `totalDeposit` can only increase.  The attack works in MSC and UDC because the balance of the user can decrease as well.

So, my suggestion is to either
a. start using monotonically increasing `deposit[user]` in addition to `balance[user]`, or
b. revert the change made for this issue

**Comment by karlb** [comment]
> a. start using monotonically increasing `deposit[user]` in addition to `balance[user]`

In that case we would only use `deposit[user]` inside the `deposit` function to calculate the `addded_deposit` and nowhere else, right. Sounds like a good way to avoid both attacks.

**Comment by pirapira** [comment]
Then let's do so in MSC and UDC.

**Comment by karlb** [comment]
I will change it in the UDC and remove the deposit handling from the MSC. The MS will check the effectiveBalance in the UDC and the MSC will use the UDC to pay out the rewards (https://github.com/raiden-network/raiden-services/issues/25).

**Comment by pirapira** [comment]
OK.  Let's close this issue when these are done.

**Comment by hackaugusto** [comment]
> a miner includes MSC's transfer() call. Now balances[beneficiary] is smaller than the user thought.

This would make the value non monotonic, please avoid this.

**Comment by pirapira** [comment]
@hackaugusto will you create a new issue about that?  The deposit function is idempotent already, satisfying this issue's closing condition.

**Comment by hackaugusto** [comment]
> @hackaugusto will you create a new issue about that? 

No need, I was under the impression the value was not monotonically increasing.
