### ISSUE TITLE
get_contracts_deployed should return all contract data

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden-contracts#774]
Check [this](https://github.com/raiden-network/raiden/issues/3670#issuecomment-476392604) comment for more info.

>The interface of the function appears to be broken. We always assume that `get_contracts_deployed()` will always return all the deployed contract addresses. It makes no sense to have to call this function twice. 

>Why not just return all deployed contracts in a dict and let the user/caller decide which one to use? You just need to populate the dict, nothing more.

>Even the docstring of the function tells me that I should expect the deployment data. [Source](https://github.com/raiden-network/raiden-contracts/blob/a299650f47ddb81de2c2bacd3d43a9af9ffcc935/raiden_contracts/contract_manager.py#L111).

**Comment by pirapira** [comment]
I'll first try to understand why it's supposed to be called twice.

**Comment by LefterisJP** [comment]
@pirapira At the moment it seems to need to be called twice. Once with `services=True` and once without if you want to get all contract deployment data in development mode. I would expect you to only need to do it once.

**Comment by pirapira** [comment]
I'll first try to understand why there are `services=True` and `services=False`.

**Comment by LefterisJP** [comment]
Good question :)

**Comment by pirapira** [comment]
Many, many functions in `raiden_contracts` now take an argument  `services:bool`.  I guess this should be turned into `module:str` and it should take `"raiden"`, `"services"`, and sometimes `"all"`.

If I completely remove these distinctions, I have to change the organization of the deployment files.  Since the Raiden contracts and service cotracts are deployed on separate commands, it makes sense to keep `deployment_kovan.json` and `deployment_services_kovan.json` separate (otherwise I have to read JSON, add elements and write it back).

**Options**

1. don't change anything
2. `get_contracts_deployed()` takes `module:str` instead of `services:bool`.  By default `module` is `"all"`.
3. completely remove the notion of modules
    1. modify JSON files in-place when deploying more contracts
    2. one JSON file contains only one contract deployment

**Comment by pirapira** [comment]
For now, I take 'get_contracts_deployed() takes module:str instead of services:bool. By default module is "all".'

But I guess the new function `get_contract_deployment_info()` should implement the new convention, and the old function should be deprecated for now.

**Comment by pirapira** [comment]
For deprecating the old function, I'm looking at https://pypi.org/project/Deprecated/ .

**Comment by pirapira** [comment]
I also see https://pypi.org/project/deprecation/.
