### ISSUE TITLE
Make sure no two different kinds of signed messages have the same byte sequence

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-contracts#907]
Perhaps it's enough to check different kinds of messages have different lengths.

**Comment by pirapira** [comment]
* closeChannel: 212
* updateNonClosingBalanceProof: 277, 212
* withdraw: 168
* coop settle 220.
* OneToN.claim: 156

There seem to be no collisions so far.

**Comment by pirapira** [comment]
In the future, either we will be careful, or we add some IDs in the message.

**Comment by hackaugusto** [comment]
@pirapira I checked the source code and using a message type is already the case, e.g.:

https://github.com/raiden-network/raiden-contracts/blob/a91642666c986ea9f5d6db61e3bab0208e7da53a/raiden_contracts/data_0.13.0/source/raiden/TokenNetwork.sol#L1563-L1572

The withdraw message has a unique value `uint256(MessageTypeId.Withdraw),` as part of its encoding. This should be sufficient to remove any errors. I would argue that we should keep as it is since it is less error prone.

**Comment by pirapira** [comment]
@hackaugusto that's about a specific client implementation.  Other clients can use `additional_hash` in different ways.

**Comment by pirapira** [comment]
@hackaugusto I see.  OneToN.claim() is not following that pattern.

**Comment by pirapira** [comment]
An issue about OneToN.claim() https://github.com/raiden-network/raiden-contracts/issues/1020 .

**Comment by pirapira** [comment]
Another issue about MonitoringService.monitor() https://github.com/raiden-network/raiden-contracts/issues/1021 .

**Comment by pirapira** [comment]
This has been done for now.
